var webpack = require('webpack');
var path = require('path');
module.exports = {
    devtool: 'inline-source-map',

    entry:{
        'index':'./src/index.js'
    },

    output:{
        //path ko resolve ani join 
        path: path.resolve(__dirname, 'dist'),
        filename: 'main.js'
    },

    //loader
    module:{
        rules:[ //multiple rules
            {   // inside create different object
                test: /\.js$/, //Starts with duita slash (//) ani forward slash 
                exclude: /node_modules/,
                use: 'babel-loader'
            }
        ]
    },
    devServer:{
        //those content that are not generated by webpack
        contentBase: path.join(__dirname, "public/"),
        port:3012,

        hot: true, //HMR reloading

        //to serve webpack files
        publicPath: "http://localhost:3012/dist/"
    }
}